# Generated by Django 5.1.1 on 2024-09-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_profile_followers_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers_count',
        ),
    ]
