# Generated by Django 5.1.1 on 2024-09-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='content',
        ),
        migrations.AddField(
            model_name='feedback',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
